package com.arthur.web.fpl;
import java.util.Date;
import java.util.Set;
import java.util.TreeSet;

/**
 * T4plFuncDef generated by MyEclipse - Hibernate Tools
 */

public class T4plFuncDef implements java.io.Serializable, Comparable {

	// Fields

	private String functionid;
	private String functiondefineid;
	private String functionname;
	private String functiondes;
	private String sldName;

	private String functionurl;

	private String parentid;
	private Long openmode;
	private Long functionorder;
	private Long functiontype;
	private String isPermit;
	private String creator;
	private Date operateTime;
	private String reserve1;
	private String reserve2;
	private String reserve3;
	private String reserve4;
	private String reserve5;

	private Set functionList = new TreeSet();

	public String getParentid() {
		return parentid;
	}

	public void setParentid(String parentid) {
		this.parentid = parentid;
	}

	public Set getFunctionList() {
		return functionList;
	}

	public void setFunctionList(Set functionList) {
		this.functionList = functionList;
	}

	/** default constructor */
	public T4plFuncDef() {
	}

	/** minimal constructor */
	public T4plFuncDef(String functionid) {
		this.functionid = functionid;
	}

	// Property accessors

	public String getFunctionid() {
		return this.functionid;
	}

	public void setFunctionid(String functionid) {
		this.functionid = functionid;
	}

	public String getFunctiondefineid() {
		return this.functiondefineid;
	}

	public void setFunctiondefineid(String functiondefineid) {
		this.functiondefineid = functiondefineid;
	}

	public String getFunctionname() {
		return this.functionname;
	}

	public void setFunctionname(String functionname) {
		this.functionname = functionname;
	}

	public String getFunctiondes() {
		return this.functiondes;
	}

	public void setFunctiondes(String functiondes) {
		this.functiondes = functiondes;
	}

	public String getSldName() {
		return this.sldName;
	}

	public void setSldName(String sldName) {
		this.sldName = sldName;
	}

	public String getFunctionurl() {
		return this.functionurl;
	}

	public void setFunctionurl(String functionurl) {
		this.functionurl = functionurl;
	}

	public Long getOpenmode() {
		return this.openmode;
	}

	public void setOpenmode(Long openmode) {
		this.openmode = openmode;
	}

	public Long getFunctionorder() {
		return this.functionorder;
	}

	public void setFunctionorder(Long functionorder) {
		this.functionorder = functionorder;
	}

	public Long getFunctiontype() {
		return this.functiontype;
	}

	public void setFunctiontype(Long functiontype) {
		this.functiontype = functiontype;
	}

	public String getIsPermit() {
		return this.isPermit;
	}

	public void setIsPermit(String isPermit) {
		this.isPermit = isPermit;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public Date getOperateTime() {
		return this.operateTime;
	}

	public void setOperateTime(Date operateTime) {
		this.operateTime = operateTime;
	}

	public String getReserve1() {
		return this.reserve1;
	}

	public void setReserve1(String reserve1) {
		this.reserve1 = reserve1;
	}

	public String getReserve2() {
		return this.reserve2;
	}

	public void setReserve2(String reserve2) {
		this.reserve2 = reserve2;
	}

	public String getReserve3() {
		return this.reserve3;
	}

	public void setReserve3(String reserve3) {
		this.reserve3 = reserve3;
	}

	public String getReserve4() {
		return this.reserve4;
	}

	public void setReserve4(String reserve4) {
		this.reserve4 = reserve4;
	}

	public String getReserve5() {
		return this.reserve5;
	}

	public void setReserve5(String reserve5) {
		this.reserve5 = reserve5;
	}

	public int compareTo(Object o) {
		if (o == null || !(o instanceof T4plFuncDef))
			return 1;
		T4plFuncDef fun = (T4plFuncDef) o;
		int orderId = this.getFunctionorder() == null ? 0 : this
				.getFunctionorder().intValue();
		int order2Id = fun.getFunctionorder() == null ? 0 : fun
				.getFunctionorder().intValue();
		if (orderId == order2Id) {
			return 1;
		} else {
			return (orderId - order2Id);
		}
	}

	public boolean equals(Object obj) {
		if (obj == null)
			return false;

		if (!(obj instanceof T4plFuncDef))
			return false;

		T4plFuncDef toCompare = (T4plFuncDef) obj;
		return toCompare.getFunctionid().equals(toCompare.getFunctionid());
	}

}